apiVersion: apps/v1
kind: Deployment
metadata:
  name: bilimili-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.cn-beijing.aliyuncs.com/bilimili/bilimili:backend_latest
          ports:
            - containerPort: 7070
            - containerPort: 7071
          env: # 指定后端的环境变量，application.yml会读取这些变量
            - name: MYSQL_HOST
              value: bilimili-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: REDIS_HOST
              value: bilimili-redis
            - name: REDIS_PORT
              value: "6379"
            - name: ELASTICSEARCH_HOST
              value: bilimili-elasticsearch
            - name: ELASTICSEARCH_PORT
              value: "9200"
---
apiVersion: v1
kind: Service
metadata:
  name: bilimili-backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 7070
      targetPort: 7070
      nodePort: 30070
    - name: websocket
      protocol: TCP
      port: 7071
      targetPort: 7071
      nodePort: 30071
  type: NodePort
