apiVersion: apps/v1
kind: Deployment
metadata:
  name: bilimili-elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0 # 使用官方 Elasticsearch 镜像
          # image: registry.cn-beijing.aliyuncs.com/bilimili/bilimili:elasticsearch_latest
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node # 设置为单节点模式
            - name: xpack.security.enabled
              value: "true"
            - name: ELASTIC_PASSWORD
              value: "BUAA13Soft"
            - name: ES_JAVA_OPTS
              value: "-Xmx512m -Xms512m"
---
apiVersion: v1
kind: Service
metadata:
  name: bilimili-elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
  type: ClusterIP
